apps/account/urls.py
from django.urls import path

from .import views


urlpatterns = [
    path('app/',views.app,name='app'),
    path('login/',views.user_login,name='user-login'),
    path('log-out/',views.user_logout,name='user-logout'),
    path('new-user/<str:random>/<str:code>/',views.new_user_registered,name='new-user'),

]


app_name = "account"

config/urls.py
from django.conf import settings

from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    # account urls
    path('a/',include('apps.account.urls',namespace='account')),
    # invite urls
    path('invite/',include('apps.invite.urls',namespace='invite')),
    path('',include('apps.page.urls',namespace='page')),
]

if settings.DEBUG: 
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    

templates/partials/_invite_modal_form.html
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Send an Invite</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
		  	<form action="." method="post">
		  		{%csrf_token %}
		  		{{ invite_form.as_p }}
		  		<button type="submit" class="btn btn-danger">Send</button>
		  	</form>
	  </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Later</button>
      </div>
    </div>
  </div>
</div>

templates/partials/_nav.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light shadow-sm fixed-top">
  <a class="navbar-brand" href="">BookInstagram</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">

    <!-- Left Nav <ul> -->
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link active-link" href="">Books</a>
      </li>
      <!--  <li class="nav-item">
        <a class="nav-link" href="#">Answer</a>
      </li> -->
      <li class="nav-item">
        <a class="nav-link" href="">Images</a>
      </li>
    </ul>

    <!-- Center Nav <ul> -->
    <ul class="nav justify-content-center">
       <li class="nav-item search-icon-span">
        <span class="nav-link"><i class="la la-search"></i></span>
       </li>
    </ul>

    <!-- Right Nav <ul> -->
    {% if request.user.is_authenticated %}
    <ul class="navbar-nav m-auto">

      <!-- New Comments -->
       <li class="nav-item">
        <span class="nav-link"><i class="la la-comments"></i></span>
       </li>

       <!-- Notification -->
       <li class="nav-item">
        <span class="nav-link"><i class="la la-bell"></i></span>
       </li>

	     <li class="nav-item dropdown dropleft">
          <!-- avatar -->
            <img src="{% if request.user.avatar_src %}{{request.user.avatar_src.url}}{% else %}{{request.user.default_avatar.url}}{% endif %}" style="cursor: pointer;max-width: 100%;height: 35px; width: 35px;" class="dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
            />
          <!-- avatar -->
        <div class="dropdown-menu shadow-sm" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="">Profile</a>
          <a class="dropdown-item" href="#">Bookmarks</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'account:user-logout' %}">Logout</a>
        </div>
      </li>
    </ul>
    {% endif %}
  </div>
</nav>